image: archlinux
packages:
  - nodejs
  - npm
sources:
  - https://github.com/haze/rehype-tree-sitter
tasks:
  - install: |
      cd rehype-tree-sitter
      npm install
  - test: |
      cd rehype-tree-sitter
      npm run test
